= About this blog
:page-layout: post
:page-date: 2020-07-31 20:15:00 +0200
:page-tags: [general,aws,lambda]
:page-liquid:

My first post on my new blog. This posts is about the blog itself and how it's made.

I created this blog to write about DevOp's things that keep me occupied. These will mainly be solutions to problems for which I had to search and try around for a long time. With this I want to achieve that others do not have to search so long for the right solution. Maybe, if I find time and motivation, I will also write articles about my work on MediathekView. And maybe I will also write articles about frameworks & technologies I am currently busy oneself with. And maybe I write articles about frameworks and technologies I'm currently working with.

The blog itself is made with https://jekyllrb.com/[Jekyll] and https://github.com/asciidoctor/jekyll-asciidoc[AsciiDoc]. It's hosted on GitHub where you can also find the source: https://github.com/nicklas2751/nicklas2751.github.io Because this don't allows to send E-Mails on server side, I created a AWS Lambda for the contact form.

This is the source of my contact form lambda:

.lambda_function.py https://github.com/Nicklas2751/contact-form-lambda/blob/c62f03067c52fdb085262a6f60b90fc3d0d1410e/lambda_function.py[view,window=_blank] https://raw.githubusercontent.com/Nicklas2751/contact-form-lambda/c62f03067c52fdb085262a6f60b90fc3d0d1410e/lambda_function.py[raw,window=_blank]
[source,python,linenums]
----
from __future__ import print_function
from botocore.exceptions import ClientError
from urllib.request import urlopen
import boto3
import json

def lambda_handler(event, context):
    if "g-recaptcha-response" in event and "mail" in event and "text" in event:
        success = checkRecaptcha(event["g-recaptcha-response"])
    else:
        success = False

    if success:
        send_email(event["mail"],event["text"])
    
    return {
        "location": event["referer"]
    }

def checkRecaptcha(captchaCode):
    data = urlopen("https://www.google.com/recaptcha/api/siteverify?secret=mySecret&response="+captchaCode).read()
    result = json.loads(data)
    return result.get('success', None)

def send_email(userMail, content):
    # Replace sender@example.com with your "From" address.
    # This address must be verified with Amazon SES.
    SENDER = "My Sender <cloud@my.domain>"

    # Replace recipient@example.com with a "To" address. If your account 
    # is still in the sandbox, this address must be verified.
    RECIPIENT = "recipient@my.domain"
    
    # If necessary, replace us-west-2 with the AWS Region you're using for Amazon SES.
    AWS_REGION = "eu-west-1"
    
    # The subject line for the email.
    SUBJECT = "A user has sent you a message"
    
    # The character encoding for the email.
    CHARSET = "UTF-8"
    
    # Create a new SES resource and specify a region.
    client = boto3.client('ses',region_name=AWS_REGION)
    
    # Try to send the email.
    try:
        #Provide the contents of the email.
        response = client.send_email(
            Destination={
                'ToAddresses': [
                    RECIPIENT
                ]
            },
            ReplyToAddresses=[
                userMail,
            ],
            Message={
                'Body': {
                    'Text': {
                        'Charset': CHARSET,
                        'Data': content,
                    },
                },
                'Subject': {
                    'Charset': CHARSET,
                    'Data': SUBJECT,
                },
            },
            Source=SENDER,
        )
    # Display an error if something goes wrong.	
    except ClientError as e:
        print(e.response['Error']['Message'])
    else:
        print("Email sent! Message ID:"),
        print(response['MessageId'])
----