name: Jekyll site CI

on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll:rw -v ${{ github.workspace }}/_site:/srv/jekyll/_site:rw \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: master
        build_dir: _site
        keep_history: true
        fqdn: nicklas.wiegandt.eu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
